---
type: showroom

default_width: 35
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: Terminal
    url: /wetty
    type: terminal
  - name: OCP Console
    url: '{openshift_cluster_console_url}'
    external: false
