---
type: showroom

default_width: 35
persist_url_state: true

tabs:
  - name: Terminal
    url: '/wetty'
    external: false
  - name: OCP Console
    url: '{openshift_cluster_console_url}'
    external: false
